[build]
  publish = "."

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"
    Permissions-Policy = "geolocation=(self), camera=(self)"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
