ALTER TABLE public.visits
  ADD COLUMN IF NOT EXISTS activity_type TEXT DEFAULT 'Visita',
  ADD COLUMN IF NOT EXISTS lat           DOUBLE PRECISION DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lng           DOUBLE PRECISION DEFAULT 0;
